### PUBLIC API TO CREATE USER###
POST http://localhost:3000/register/user
Content-Type: application/json

{
  "username": "syahirah",
  "password": "syahirah12345",
  "name": "Syahirah",
  "officerno": "123456",
  "rank": "Captain",
  "phone": "1234567890"
}

### PUBLIC API TO LOGIN USER ###
POST http://localhost:3000/login/user
Content-Type: application/json

{
  "username": "syahirah",
  "password": "syahirah12345"
}

##### PUBLIC API TO VIEW VISITOR####
GET http://localhost:3000/viewvisitor
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC
{
    
}

## PUBLIC API TO ISSUE PASS ##

GET http://localhost:3000/issuevisitorpass
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC
{
    
}

## PUBLIC API TO RETRIEVE PASS##

GET http://localhost:3000/retrievevisitorpass
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC
{
    
}

