### PUBLIC API TO CREATE USER###
POST https://visitorwebappis.azurewebsites.net/register/user
Content-Type: application/json

{
  "username": "syahirah",
  "password": "syahirah12345",
  "name": "Syahirah",
  "officerno": "123456",
  "rank": "Captain",
  "phone": "1234567890"
}

### PUBLIC API TO LOGIN USER ###
POST https://visitorwebappis.azurewebsites.net/login/user
Content-Type: application/json

{
  "username": "syahirah",
  "password": "syahirah12345"
}

##### PUBLIC API TO VIEW VISITOR####
GET https://visitorwebappis.azurewebsites.net/viewvisitor
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC



## PUBLIC API TO ISSUE PASS ##

GET https://visitorwebappis.azurewebsites.net/issuevisitorpass
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC
{
    
}

## PUBLIC API TO RETRIEVE PASS##

GET https://visitorwebappis.azurewebsites.net/retrievevisitorpass
Content-Type: application/json
Authorization: Bearer $2b$10$zYmKW48fDeIkQz4IbvP6qON3cEVG1tCqRsYL451jGWAMOxoj8H6nC
{
    
}

